commands:
  # Hora
  - command:
    input:  Que horas são?
    entity: time
    action: getTime
  - command:
    input:  Me diga as horas.
    entity: time
    action: getTime
  - command:
    input:  Informe horas.
    entity: time
    action: getTime
  # Data
  - command:
    input:  Qual é a data de hoje?
    entity: time
    action: getDate
  - command:
    input:  Data de hoje.
    entity: time
    action: getDate
  - command:
    input:  Informe a data de hoje.
    entity: time
    action: getDate
  # Abrir
  # Bloco de notas
  - command:
    input:  Abrir bloco de notas
    entity: open
    action: notepad
  - command:
    input:  Abra o bloco de notas
    entity: open
    action: notepad
  # Word
  - command:
    input:  Abrir o word
    entity: open
    action: word
  - command:
    input:  Abra o word
    entity: open
    action: word
  # Google Chrome
  - command:
    input:  Abrir o chrome
    entity: open
    action: chrome
  - command:
    input:  Abra o chrome
    entity: open
    action: chrome
  # Windows Media Player
  - command:
    input:  Abrir o reprodutor de mídia
    entity: open
    action: wMP
  - command:
    input:  Abra o reprodutor de mídia
    entity: open
    action: wMP